### ISSUE TITLE
Manga image hidden behind menu in iOS

### ISSUE THREAD

**Issue by noraesae** [isairz/yomiko#10]
In the viewer, images are hidden behind the menu in iOS Safari and the menu doesn't hide, maybe because touch is prevented by `preventDefault`.

![screen shot 2015-11-26 at 23 00 51](https://cloud.githubusercontent.com/assets/1013641/11424582/953a1108-9491-11e5-920e-aff6e8893a3c.png)

**Comment by isairz** [comment]
Fixed. 62dfe732df51807aa84a6ccfe5e666470e9153e0

**Comment by isairz** [comment]
This issue is related with [this article](http://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html)
