### ISSUE TITLE
Do not work in Node 5

### ISSUE THREAD

**Issue by utatti** [isairz/yomiko#8]
Works well with Node 4, but not with 5. There may be some dependencies not compatible with Node 5. No problem to use Node 4, but just to notice.

**Comment by isairz** [comment]
After dependencies upgrade, In contrast, it works well with Node 5 & npm3, but not with Node 4 & npm 2.

Error logs say dependencies couldn't find their dependencies even though those are in package.json.
I steel don't know what is real problem.
